import type { NextPage } from 'next';
import Head from 'next/head';
import { Form } from '../components/Form';

const Home: NextPage = () => {
  return (
    <div className="flex flex-col mx-auto md:max-w-screen-xl">
      <Head>
        <title>Sebo Brasil - Desafio Dev.FullStack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-6">
        <h1 className="text-2xl mb-5">Desafio Dev.FullStack</h1>

        <section>
          <Form />
        </section>
      </main>
    </div>
  );
};

export default Home;
